title: On your desk
tagline: opinions, tech, examination and popular culture
description: Opinions, tech, examination and popular culture.

markdown: kramdown
show_drafts: false
url: http://blog.lcfg.me
permalink: /:year/:month/:day/:title.htm

safe: true
lsi: false
highlighter: kramdown
timezone: Europe/Amsterdam
encoding: UTF-8
keep_files:  ['.git','.svn']
future: true
markdown_ext:  markdown,mkd,mkdn,md,

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

owner:
  name:       Laurens Greven
  email:      laurens.greven@hva.nl
  twitter:      lcf_g
  github:       lcfg



post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/
